server:
  port: 8080
  context-path: /mysketch
spring:
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:file:/Users/zhipingwang/workspace/idea/my_spring_sketch/aa
        #username:
        #password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


